### ISSUE TITLE
monero-lws image not working for M1 mac

### ISSUE THREAD

**Issue by LeoNero** [farcaster-project/containers#63]
Error: `qemu uncaught target signal 4 (illegal instruction) - core dumped docker` when trying to run a container.

Maybe a fix could be similar to https://github.com/vtnerd/monero-lws/pull/43/

**Comment by h4sh3d** [comment]
If a patch exists it should be applied (for now) on @TheCharlatan fork of vtnerd lws.

**Comment by LeoNero** [comment]
I'll take a look at it later. For now, I am running it without docker :)
